version: '3.2'

services:
  database:
    image: postgres:10.4
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'database_name'
      PGDATA: '/var/lib/postgresql/data'
      PGCLIENTENCODING: 'UTF8'
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    ports:
      - 54322:5432

  phoenix:
    image: elixir:1.7.4-alpine
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: database_name
      PGPORT: 5432
      PGHOST: database
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - '4002:4000'
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - database
  # phoenix:
  #   build: .
  #   environment:
  #     PGUSER: postgres
  #     PGPASSWORD: postgres
  #     PGDATABASE: database_name
  #     PGPORT: 5432
  #     PGHOST: database
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - database
