version: '3.2'

services:
  database:
    container_name: database
    image: postgres:10.4
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'waller_database'
      PGDATA: '/var/lib/postgresql/data'
      PGCLIENTENCODING: 'UTF8'
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    ports:
      - 54322:5432

  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - 6379:6379

  phoenix:
    container_name: phoenix
    build: ./waller
    environment:
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
      PGDATABASE: 'waller_database'
      PGPORT: 5432
      PGHOST: 'database'
      PGTESTDATABASE: waller_test_database
      # Redis configs
      REDIS_HOST: 'redis'
      REDIS_PORT: 6979
      REDIS_CACHE_TIME: 600

      ALLOWED_HOST: 'http"//front:5000'
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - '4000:4000'
    depends_on:
      - database
      - redis
    # USE THIS OPTIONS WHEN WORKING ON DEV MODE
    # volumes:
    #   - ./:/app/
    # working_dir: /app

  front:
    container_name: front
    build: ./waller-front
    environment:
      API_URL: http://phoenix:4000
      RECAPTCHA_KEY: 6Ldlm4UUAAAAAGLrxcMRgCl1X965NY0W2ikpZi5z
    ports:
      - '5000:5000'
    depends_on:
      - phoenix
    # USE THIS OPTIONS WHEN WORKING ON DEV MODE
    # restart: always
    # tty: true
    # volumes:
    #   - ./:/app/
    # working_dir: /app
